<?php

declare(strict_types=1);

namespace KVS\CLI\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Generates shell completion scripts.
 *
 * Works in PHAR by embedding scripts directly instead of reading from Resources/.
 */
class CompletionCommand extends Command
{
    protected function configure(): void
    {
        $this
            ->setName('completion')
            ->setDescription('Dump the shell completion script')
            ->addArgument('shell', InputArgument::OPTIONAL, 'The shell type (bash, zsh, fish)', $this->guessShell())
            ->setHelp(<<<'HELP'
Generate shell completion script.

<info>Bash:</info>
  <comment>kvs completion bash >> ~/.bash_completion</comment>
  Or system-wide:
  <comment>kvs completion bash | sudo tee /etc/bash_completion.d/kvs</comment>

<info>Zsh:</info>
  <comment>kvs completion zsh > ~/.zsh/completion/_kvs</comment>
  Make sure <comment>~/.zsh/completion</comment> is in your <comment>$fpath</comment>

<info>Fish:</info>
  <comment>kvs completion fish > ~/.config/fish/completions/kvs.fish</comment>

After installation, restart your shell or run:
  <comment>source ~/.bashrc</comment> (bash)
  <comment>source ~/.zshrc</comment> (zsh)
HELP
            );
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $shell = $input->getArgument('shell');

        $script = match ($shell) {
            'bash' => $this->getBashScript(),
            'zsh' => $this->getZshScript(),
            'fish' => $this->getFishScript(),
            default => null,
        };

        if ($script === null) {
            $output->writeln(sprintf('<error>Shell "%s" not supported. Use bash, zsh, or fish.</error>', $shell));
            return Command::FAILURE;
        }

        $output->write($script, false, OutputInterface::OUTPUT_RAW);

        return Command::SUCCESS;
    }

    private function guessShell(): string
    {
        $shell = basename((string) getenv('SHELL'));
        return in_array($shell, ['bash', 'zsh', 'fish'], true) ? $shell : 'bash';
    }

    private function getBashScript(): string
    {
        return <<<'BASH'
# KVS CLI bash completion
# Generated by kvs completion bash

_kvs_complete() {
    local cur prev words cword
    _init_completion -n : || return

    local commands="help list self-update completion
        system:status system:cache system:cron system:backup system:check
        maintenance
        video album user category tag comment model dvd
        plugin config shell eval eval-file
        db:export db:import
        dev:debug dev:log
        video:formats video:screenshots"

    local video_actions="list show"
    local album_actions="list show"
    local user_actions="list show"
    local category_actions="list"
    local tag_actions="list"
    local comment_actions="list show stats"
    local model_actions="list show"
    local dvd_actions="list show"
    local plugin_actions="list show path status"
    local config_actions="list get"
    local cache_actions="clear status"
    local maintenance_actions="on off status"
    local debug_actions="on off status"

    if [[ ${cword} -eq 1 ]]; then
        COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
        return
    fi

    case "${words[1]}" in
        video)
            COMPREPLY=($(compgen -W "${video_actions}" -- "${cur}"))
            ;;
        album)
            COMPREPLY=($(compgen -W "${album_actions}" -- "${cur}"))
            ;;
        user)
            COMPREPLY=($(compgen -W "${user_actions}" -- "${cur}"))
            ;;
        category)
            COMPREPLY=($(compgen -W "${category_actions}" -- "${cur}"))
            ;;
        tag)
            COMPREPLY=($(compgen -W "${tag_actions}" -- "${cur}"))
            ;;
        comment)
            COMPREPLY=($(compgen -W "${comment_actions}" -- "${cur}"))
            ;;
        model)
            COMPREPLY=($(compgen -W "${model_actions}" -- "${cur}"))
            ;;
        dvd)
            COMPREPLY=($(compgen -W "${dvd_actions}" -- "${cur}"))
            ;;
        plugin)
            COMPREPLY=($(compgen -W "${plugin_actions}" -- "${cur}"))
            ;;
        config)
            COMPREPLY=($(compgen -W "${config_actions}" -- "${cur}"))
            ;;
        system:cache)
            COMPREPLY=($(compgen -W "${cache_actions}" -- "${cur}"))
            ;;
        maintenance)
            COMPREPLY=($(compgen -W "${maintenance_actions}" -- "${cur}"))
            ;;
        dev:debug)
            COMPREPLY=($(compgen -W "${debug_actions}" -- "${cur}"))
            ;;
        *)
            COMPREPLY=($(compgen -W "--help --path --format --fields --limit" -- "${cur}"))
            ;;
    esac
}

complete -F _kvs_complete kvs
BASH;
    }

    private function getZshScript(): string
    {
        return <<<'ZSH'
#compdef kvs

# KVS CLI zsh completion
# Generated by kvs completion zsh

_kvs() {
    local -a commands
    commands=(
        'help:Display help for a command'
        'list:List commands'
        'self-update:Update KVS CLI to latest version'
        'completion:Dump shell completion script'
        'system\:status:Show system status'
        'system\:cache:Manage cache'
        'system\:cron:Run cron tasks'
        'system\:backup:Create backup'
        'system\:check:Check system health'
        'maintenance:Manage maintenance mode'
        'video:Manage videos'
        'album:Manage albums'
        'user:Manage users'
        'category:Manage categories'
        'tag:Manage tags'
        'comment:Manage comments'
        'model:Manage models'
        'dvd:Manage DVDs'
        'plugin:Manage plugins'
        'config:View configuration'
        'shell:Interactive PHP shell'
        'eval:Execute PHP code'
        'eval-file:Execute PHP file'
        'db\:export:Export database'
        'db\:import:Import database'
        'dev\:debug:Toggle debug mode'
        'dev\:log:View logs'
        'video\:formats:Show video formats'
        'video\:screenshots:Manage screenshots'
    )

    _arguments -C \
        '--path=[Path to KVS installation]:directory:_files -/' \
        '--help[Display help]' \
        '1: :->command' \
        '*:: :->args'

    case $state in
        command)
            _describe -t commands 'kvs command' commands
            ;;
        args)
            case $words[1] in
                video|album|user|model|dvd)
                    _arguments '1:action:(list show)'
                    ;;
                category|tag)
                    _arguments '1:action:(list)'
                    ;;
                comment)
                    _arguments '1:action:(list show stats)'
                    ;;
                plugin)
                    _arguments '1:action:(list show path status)'
                    ;;
                config)
                    _arguments '1:action:(list get)'
                    ;;
                system:cache)
                    _arguments '1:action:(clear status)'
                    ;;
                maintenance|dev:debug)
                    _arguments '1:action:(on off status)'
                    ;;
            esac
            ;;
    esac
}

_kvs "$@"
ZSH;
    }

    private function getFishScript(): string
    {
        return <<<'FISH'
# KVS CLI fish completion
# Generated by kvs completion fish

# Disable file completion by default
complete -c kvs -f

# Main commands
complete -c kvs -n "__fish_use_subcommand" -a "help" -d "Display help"
complete -c kvs -n "__fish_use_subcommand" -a "list" -d "List commands"
complete -c kvs -n "__fish_use_subcommand" -a "self-update" -d "Update KVS CLI"
complete -c kvs -n "__fish_use_subcommand" -a "completion" -d "Shell completion"
complete -c kvs -n "__fish_use_subcommand" -a "system:status" -d "System status"
complete -c kvs -n "__fish_use_subcommand" -a "system:cache" -d "Manage cache"
complete -c kvs -n "__fish_use_subcommand" -a "system:cron" -d "Run cron"
complete -c kvs -n "__fish_use_subcommand" -a "system:backup" -d "Create backup"
complete -c kvs -n "__fish_use_subcommand" -a "system:check" -d "Check health"
complete -c kvs -n "__fish_use_subcommand" -a "maintenance" -d "Maintenance mode"
complete -c kvs -n "__fish_use_subcommand" -a "video" -d "Manage videos"
complete -c kvs -n "__fish_use_subcommand" -a "album" -d "Manage albums"
complete -c kvs -n "__fish_use_subcommand" -a "user" -d "Manage users"
complete -c kvs -n "__fish_use_subcommand" -a "category" -d "Categories"
complete -c kvs -n "__fish_use_subcommand" -a "tag" -d "Manage tags"
complete -c kvs -n "__fish_use_subcommand" -a "comment" -d "Manage comments"
complete -c kvs -n "__fish_use_subcommand" -a "model" -d "Manage models"
complete -c kvs -n "__fish_use_subcommand" -a "dvd" -d "Manage DVDs"
complete -c kvs -n "__fish_use_subcommand" -a "plugin" -d "Manage plugins"
complete -c kvs -n "__fish_use_subcommand" -a "config" -d "Configuration"
complete -c kvs -n "__fish_use_subcommand" -a "shell" -d "PHP shell"
complete -c kvs -n "__fish_use_subcommand" -a "eval" -d "Execute PHP"
complete -c kvs -n "__fish_use_subcommand" -a "eval-file" -d "Execute PHP file"
complete -c kvs -n "__fish_use_subcommand" -a "db:export" -d "Export database"
complete -c kvs -n "__fish_use_subcommand" -a "db:import" -d "Import database"
complete -c kvs -n "__fish_use_subcommand" -a "dev:debug" -d "Debug mode"
complete -c kvs -n "__fish_use_subcommand" -a "dev:log" -d "View logs"

# Subcommand actions
complete -c kvs -n "__fish_seen_subcommand_from video album user model dvd" -a "list show"
complete -c kvs -n "__fish_seen_subcommand_from category tag" -a "list"
complete -c kvs -n "__fish_seen_subcommand_from comment" -a "list show stats"
complete -c kvs -n "__fish_seen_subcommand_from plugin" -a "list show path status"
complete -c kvs -n "__fish_seen_subcommand_from config" -a "list get"
complete -c kvs -n "__fish_seen_subcommand_from system:cache" -a "clear status"
complete -c kvs -n "__fish_seen_subcommand_from maintenance dev:debug" -a "on off status"
complete -c kvs -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"

# Global options
complete -c kvs -l path -d "Path to KVS installation" -r
complete -c kvs -l help -d "Display help"
complete -c kvs -l format -d "Output format" -a "table json csv yaml count ids"
complete -c kvs -l fields -d "Fields to display" -r
complete -c kvs -l limit -d "Limit results" -r
FISH;
    }
}
